prod:
  hostname: mihost.com
  user: cpanel-user
  port: 22
  configFile: /Users/user/.ssh/config
  identityFile: ~/.ssh/id_rsa
  forwardAgent: true
  multiplexing: true
  stage: prod
  roles:
    - app
    - db
  deploy_path: ~/projectpath